### ISSUE TITLE
Suggestion: Update README recommending disabling macos and windows in github actions

### ISSUE THREAD

**Issue by brad-getpassport** [jenstroeger/python-package-template#124]
I would recommend that the README file call out that anyone forking/copying this repository disable the windows and macos checking for github actions.

Per this link: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

Checking on those two variants is quite expensive on _**Github actions**_ minutes and $, so I would not recommend it as you can eat through your allocated minutes and money quickly.

**Comment by jenstroeger** [comment]
@brad-getpassport — you’re absolutely correct: after about a week we disabled the macOS runner at [Firebrand](https://github.com/FirebrandTech) because it charged up to 40¢ per run _on every commit_ and the Windows runner up to 51¢ 😳 

Considering we run two of each — one for Python 3.9 and one for 3.10 — that’s quite a bit of money if people push several commits a day.

**Comment by jenstroeger** [comment]
@brad-getpassport please see PR #189.

**Comment by jenstroeger** [comment]
Commit https://github.com/jenstroeger/python-package-template/commit/e521f017a8fae4a0c050968921c2d2d8ab5bdd7e
