### ISSUE TITLE
Merge issues with CHANGELOG.md and dervied repo

### ISSUE THREAD

**Issue by acrobat888** [jenstroeger/python-package-template#31]
I think there should be separate CHANGELOG.md files for the template and the _**derived**_ repo's from this template.  Could we have a different name like TEMPLATE_CHANGELOG.md and then reserve CHANGELOG.md for the _**derived**_ packages and repos?

If that's not possible, how can we get the CHANGELOG.md file to have the template's changes segregated or integrated in a way that makes merging the template into _**derived**_ repos easier.

**Comment by jenstroeger** [comment]
Thanks @acrobat888! Looks like this issue is closely related to #30.

This repo’s workflow uses the [python-semantic-release](https://github.com/relekang/python-semantic-release) package:

https://github.com/jenstroeger/python-package-template/blob/b7580d28186a2c9333031e202eec1e5be668e624/.github/workflows/check-and-release-main.yml#L38-L42

and according to [the documentation](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#config-changelog-file) there’s a `changelog_file` option that we can use in our configuration:

https://github.com/jenstroeger/python-package-template/blob/b7580d28186a2c9333031e202eec1e5be668e624/pyproject.toml#L36-L40

and add

```
changelog_file = TEMPLATE_CHANGELOG.md
```

which users/forks of this repo would then have to modify.

Luckily, it looks like Github doesn’t make assumptions about a CHANGELOG.md file (like it does about a README.md file that it shows on a repo’s landing page, see issue #30).
